# Generated by Django 5.0.6 on 2024-07-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='group_data',
            new_name='group_users',
        ),
    ]
