# Generated by Django 5.0.6 on 2024-07-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_group_data_groups_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_code',
            field=models.CharField(default='code', max_length=10),
            preserve_default=False,
        ),
    ]
