# Generated by Django 5.0.6 on 2024-07-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_groups_group_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='group_history',
        ),
    ]
