# Generated by Django 5.0.6 on 2024-08-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_groups_group_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_history',
            field=models.JSONField(null=True),
        ),
    ]
